In [39]:
import pandas as pd
import numpy as np
import glob

from bokeh.palettes import Spectral4
from bokeh.plotting import figure, show
from bokeh.palettes import Category10, Category20, Category20b, Category20c
from bokeh.palettes import Greys256, Inferno256, Magma256, Plasma256

# Loading the data

In [40]:
#load the datasets and combine

extension = 'csv'
all_filenames = [i for i in glob.glob('scraped_data/*.{}'.format(extension))]

In [41]:
relevant_cols = ['@context',
 '@type',
 'availability',
 'brand',
 'date',
 'description',
 'image',
 'name',
 'offers',
 'price',
 'priceCurrency',
 'priceValidUntil',
 'sku',
 'url']

In [42]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f)[relevant_cols] for f in all_filenames ])

#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False)

# Analysis

In [43]:
combined_csv.shape

(5747, 14)

In [44]:
combined_csv.columns

Index(['@context', '@type', 'availability', 'brand', 'date', 'description',
       'image', 'name', 'offers', 'price', 'priceCurrency', 'priceValidUntil',
       'sku', 'url'],
      dtype='object')

In [45]:
combined_csv

,@context,@type,availability,brand,date,description,image,name,offers,price,priceCurrency,priceValidUntil,sku,url
0,http://schema.org,Offer,https://schema.org/InStock,{'name': 'FFG'},2021-02-01,Health benefits of Amla-:\n\n\nIt improves eye...,"{'@type': 'ImageObject', 'url': 'https://cdn.s...",Default Title,"[{'@type': 'Offer', 'name': 'Default Title', '...",18.00,INR,2021-02-11,AM2,https://fastandfresh.in/products/amla?variant=...
1,http://schema.org,Offer,https://schema.org/InStock,{'name': 'FFG'},2021-02-01,Health benefits of pomegranate (Anar)-:\n\n\nP...,"{'@type': 'ImageObject', 'url': 'https://cdn.s...",Default Title,"[{'@type': 'Offer', 'name': 'Default Title', '...",128.00,INR,2021-02-11,AN1,https://fastandfresh.in/products/anar-kandhari...
2,http://schema.org,Offer,https://schema.org/InStock,{'name': 'FFG'},2021-02-01,Interesting Health Benefits Of Golden Apple-:\...,"{'@type': 'ImageObject', 'url': 'https://cdn.s...",Default Title,"[{'@type': 'Offer', 'name': 'Default Title', '...",139.00,INR,2021-02-11,AP4,https://fastandfresh.in/products/apple-golden-...
3,http://schema.org,Offer,https://schema.org/InStock,{'name': 'FFG'},2021-02-01,Some amazing Health benefits of (Apple grenny ...,"{'@type': 'ImageObject', 'url': 'https://cdn.s...",Default Title,"[{'@type': 'Offer', 'name': 'Default Title', '...",112.00,INR,2021-02-11,AP1,https://fastandfresh.in/products/apple-green-i...
4,http://schema.org,Offer,https://schema.org/InStock,{'name': 'FFG'},2021-02-01,Surprising and Impressive Health Benefits of A...,"{'@type': 'ImageObject', 'url': 'https://cdn.s...",Default Title,"[{'@type': 'Offer', 'name': 'Default Title', '...",195.00,INR,2021-02-11,AP9,https://fastandfresh.in/products/apple-shimla-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,https://schema.org,Offer,https://schema.org/InStock,"{'@type': 'Brand', 'name': 'FAST AND FRESH GLO...",2021-01-11,Introducing FFG VITAMIN-C COMBO to boost your ...,https://cdn.shopify.com/s/files/1/0279/6876/60...,VITAMIN-C COMBO,"[{'@type': 'Offer', 'price': '699.00', 'priceC...",699,INR,2021-02-10,NaN,https://fastandfresh.in/products/vitamin-c-com...
157,https://schema.org,Offer,https://schema.org/InStock,"{'@type': 'Brand', 'name': 'FFG'}",2021-01-11,\nHere are the top health benefits of eating w...,https://cdn.shopify.com/s/files/1/0279/6876/60...,Water Melon (Price per Pcs 2.5kg to 3kg),"[{'@type': 'Offer', 'price': '39.00', 'priceCu...",39,INR,2021-02-10,WA1,https://fastandfresh.in/products/water-melon?v...
158,https://schema.org,Offer,https://schema.org/InStock,"{'@type': 'Brand', 'name': 'FFG'}",2021-01-11,\n\nZespri kiwifruit are an excellent source o...,https://cdn.shopify.com/s/files/1/0279/6876/60...,Zespri Green Kiwi (Price per Box of 4 pcs),"[{'@type': 'Offer', 'price': '196.00', 'priceC...",196,INR,2021-02-10,KZG,https://fastandfresh.in/products/zesperi-green...
159,https://schema.org,Offer,https://schema.org/InStock,"{'@type': 'Brand', 'name': 'FFG'}",2021-01-11,Here are evidence-based benefits of zucchini....,https://cdn.shopify.com/s/files/1/0279/6876/60...,Zuchini Green (Price per 500 gms),"[{'@type': 'Offer', 'price': '29.00', 'priceCu...",29,INR,2021-02-10,ZU1,https://fastandfresh.in/products/zuchini-green...
160,https://schema.org,Offer,https://schema.org/InStock,"{'@type': 'Brand', 'name': 'FFG'}",2021-01-11,Here are evidence-based benefits of zucchini....,https://cdn.shopify.com/s/files/1/0279/6876/60...,Zuchini Yellow (Price per 250gms),"[{'@type': 'Offer', 'price': '24.00', 'priceCu...",24,INR,2021-02-10,ZU2,https://fastandfresh.in/products/zuchini-yello...

## Plot trends of some items

In [46]:
items_list = combined_csv['name'].unique()
items_list = ['Zuchini Green (Price per 500 gms)',
              'Zuchini Yellow (Price per 250gms)',
              'Raspberry/Cape Goosberry (Price per 250gms)',
              'avacados','asparagus-thai']

In [47]:
p = figure(plot_width=1400, plot_height=600, x_axis_type="datetime")
p.title.text = 'Click on legend entries to mute the corresponding lines'

for name, color in zip(items_list, Inferno256):
    df = combined_csv[combined_csv['name']==name].reset_index(drop=True)
    df.sort_values(by='date',inplace=True)
    df['date'] = pd.to_datetime(df['date'])
    p.line(df['date'], df['price'], line_width=2, color=color, alpha=0.8,
           muted_color=color, muted_alpha=0.2, legend_label=name)

p.legend.location = "top_left"
p.legend.click_policy="mute"

show(p)

In [48]:
for name, color in zip(items_list, Inferno256):
    print (name,color)

Zuchini Green (Price per 500 gms) #000003
Zuchini Yellow (Price per 250gms) #000004
Raspberry/Cape Goosberry (Price per 250gms) #000006
avacados #010007
asparagus-thai #010109

## Item counts by day

In [49]:
pd.pivot_table(combined_csv,index='date',values='name',aggfunc=len)

            name
date
2020-12-28   154
2020-12-29   154
2020-12-30   155
2020-12-31   156
2021-01-01   157
2021-01-02   157
2021-01-03   157
2021-01-04   157
2021-01-05   157
2021-01-06   157
2021-01-07   159
2021-01-08   160
2021-01-09   160
2021-01-10   160
2021-01-11   161
2021-01-12   160
2021-01-13   159
2021-01-14   160
2021-01-15   160
2021-01-16   162
2021-01-18   162
2021-01-19   162
2021-01-20   162
2021-01-21   164
2021-01-22   164
2021-01-23   163
2021-01-25   162
2021-01-26   162
2021-01-27   162
2021-01-28   162
2021-01-29   161
2021-01-30   161
2021-01-31   161
2021-02-01   158
2021-02-02   159
2021-02-03   160

## New items added recently

In [50]:
l1 = combined_csv[combined_csv['date']=='2021-01-20']['name'].to_list()
l2 = combined_csv[combined_csv['date']=='2021-02-01']['name'].to_list()

In [51]:
new_list = np.setdiff1d(l2,l1)
new_list

array(['Default Title'], dtype='<U13')